### PR TITLE
Mcts

### PR DESCRIPTION
**Pull request by Arie3301**
Needed to add options and agent member variables (with corresponding getters). Ideally my future commits will concern the search class only (at least until that class is done).

In a commit I noted that search is implemented as a standalone fn and that it might make more sense to make it a class method for Agent. What do you think?

### CODE REVIEW

**Comment by surajx** [comment]
I'll review this tomorrow night. 
I would do a lot more refactoring to the base code this week to add separation of concerns and to basically restructure the current architecture. 

To quickly answer your question, an agent plans using MCTS, the search part needs to know only the internal model of the environment, which is the CTW. So I would have an instance of MCTS in the agent, as we discussed the MCTS should maintain the simulation of the env to do smart update later-on. Also I would like an agent.getAction() call to in-turn call mctsInstance.search(ctw_instance), which should return an action. 

Let me know if anything was confusing, drop a reply, or we can discuss tomorrow after 7pm.

**Comment by Arie3301** [comment]
Do you want to discuss this tonight at 8:30pm?

**Comment by surajx** [comment]
:+1:

**Review by surajx — APPROVED** [review]
:+1:

**Pull request merged**
